import localFont from "next/font/local";
const myFont = localFont({ src: "../assets/fonts/Poppins-Regular.ttf" });
// const myFont = localFont({ src: "../assets/fonts/Inter-Regular.ttf" });

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={myFont.className}>
          <div className="p-10">{children}</div>
      </body>
    </html>
  );
}
